config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 'posts/new' , to: 'posts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cake_controller.rb
class CakeController < ApplicationController
  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def edit 
    @user = User.find(params[:id])
  end

end

app/controllers/smoothie_controller.rb
class SmoothieController < ApplicationController
  def 
    new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cake_helper.rb
module CakeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/smoothie_helper.rb
module SmoothieHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ViewDrill
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/index.html.haml
.Wapper
  = image_tag ('HIMARI_alexander-sporre-photography-15.jpg' ), class:'Wapper__Top_image'
  .Wapper__Top_image__box 
    .Wapper__Top_image__box__name
      HimaRi
.Wapper__bottom
  = link_to 'Cake' , posts_new_path , class:'list'
  = link_to 'Smoothie' , '#' ,  class:'list'
  = link_to 'Lunch' , '#' ,  class:'list'
  = link_to 'Event' , '#' , class:'list'

app/views/posts/new.html.haml
.Wapper
  .Wapper__side
    = image_tag 'ケーキ　３段.jpg' 
  .Wapper__main
    order cake
    .Wapper__main__sub
      Make only one cake in the world,for you
      .Wapper__main__sub__contents
        %div 当店が大切にしていること
        %div 喜んでもらえる顔がみたい。ただその一つに尽きます。
        %div 当店は全ての材料は国産の材料を使用しております。
        %div タルト生地、スポンジ生地、全て手作りしております。
        %div 生クリームも北海道産の純生クリームを使用しております。
        %div アレルギー等にも細かく対応いたします。
        %div 大切な記念日のケーキをぜひ当店に
    .Wapper__main__sub
      From the button below

      
  .Wapper__memo
= image_tag 'B559195C-C1F6-40E1-A8D3-AF3622F3AA1D_4_5005_c.jpeg',class:'cake_img'
= image_tag 'IMG_0682.JPG',class:'cake_img'
= image_tag '1A14B5A5-BD03-4977-9A9B-00A2ADA4CF5A_1_105_c.jpeg',class:'cake_img'
= image_tag '621E3147-0B2D-4A89-8D2C-BDF15EEC0C7D_1_105_c.jpeg',class:'cake_img'
= image_tag '4DEB088C-9575-43FA-98E5-32012ABD4F82_1_105_c.jpeg',class:'cake_img'
= image_tag '57A03419-FAF3-4921-BBD0-50EBC6EB849A_4_5005_c.jpeg',class:'cake_img'
= image_tag 'C7EB8CDC-3835-4C8A-AF7F-6B6F83351569_1_105_c.jpeg',class:'cake_img'
= image_tag 'E94E8629-1F51-4DC0-8D28-57A3C5AC3522_1_105_c.jpeg',class:'cake_img'
= image_tag 'Pic.ARALE.png',class:'cake_img'
= image_tag 'Pic.kuu_ohana.png',class:'cake_img'
= image_tag '7EF5C200-BBD5-480D-A3AD-B0C537D5C553_1_105_c.jpeg',class:'cake_img'
= image_tag 'C9351ABF-0597-4B92-8BFF-F0943FD7C327_1_105_c.jpeg',class:'cake_img'
  .Wapper__bottom
    %form_for do |f|
      %f.text_field :name 
      %f.submit 